service: PyTorch-Example-Service-3

provider:
  name: aws
  runtime: python3.8
  stage: car-grading
  region: eu-west-1
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/AdministratorAccess # not sure why this is ignored

plugins:
  - serverless-deployment-bucket # TODO don't need this
  # - serverless-python-requirements
  # - serverless-prune-plugin

# custom:
#   pythonRequirements:
#     usePoetry: false
#     dockerizePip: non-linux
#     dockerSsh: true
#     noDeploy: []
#     layer:
#       name: ${self:service}-car-grading-layer
#       description: Lambda layer with dependencies (installed from Pipfile)
#       compatibleRuntimes:
#         - python3.8

package:
  excludeDevDependencies: True
  exclude:
    - __pycache__/**
    - node_modules/**
    - package.json
    - package-lock.json
    - README.md
    - README2.md
    - layers/**
    - .vscode
    - scripts

# layers:
#   PyTorch:
#     package:
#       artifact: layers/PyTorch.zip
#     compatibleRuntimes:
#       - python3.8

functions:
  pytorch-example:
    handler: src/main.main
    timeout: 30
    memorySize: 10000
    ephemeralStorageSize: 3000 # not sure why this is ignored
    layers:
      - arn:aws:lambda:eu-west-1:266047756759:layer:PyTorch:2
      # - { Ref: PythonRequirementsLambdaLayer }
      # - { Ref: PyTorchLambdaLayer }
    events:
      - http:
          method: post
          path: car-grading/grade
